version: "2"

services:
  db-service:
    build: .
    image: db-service
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8080:8080"
    links:
      - postgres:postgres
  postgres:
    build: ../postgres
